apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
 name: fortio-container-executor
 namespace: testkube
spec:
 types:
 - playwright-container/test
 executor_type: container
 image: kubeshop/testkube-playwright-executor:latest
 command:
 - npx playwright test --project=wip2
 #- <PLAYWRITE_COMMAND>